export const initialPlayers = [
  {
    id: "PL-2026-001",
    name: "James Anderson",
    team: "Thunder Strikers",
    position: "Spiker",
    jerseyNumber: "12",
    contactNumber: "+94 77 111 2222",
    status: "Active",
    email: "james.anderson@thunderstrikers.com",
    dateOfBirth: "2000-05-12",
    gender: "Male",
    height: "192",
    weight: "85",
    address: "123 Galle Road, Colombo 03",
    photoUrl: null
  },
  {
    id: "PL-2026-002",
    name: "Sarah Kim",
    team: "Ocean Waves",
    position: "Setter",
    jerseyNumber: "7",
    contactNumber: "+94 77 222 3333",
    status: "Active",
    email: "sarah.kim@oceanwaves.com",
    dateOfBirth: "2002-09-24",
    gender: "Female",
    height: "178",
    weight: "68",
    address: "45 Marine Drive, Galle",
    photoUrl: null
  },
  {
    id: "PL-2026-003",
    name: "Michael Chen",
    team: "Sky Hawks",
    position: "Blocker",
    jerseyNumber: "9",
    contactNumber: "+94 77 333 4444",
    status: "Active",
    email: "michael.chen@skyhawks.com",
    dateOfBirth: "1999-11-05",
    gender: "Male",
    height: "198",
    weight: "92",
    address: "78 Peradeniya Road, Kandy",
    photoUrl: null
  },
  {
    id: "PL-2026-004",
    name: "Emily Davis",
    team: "Net Ninjas",
    position: "Libero",
    jerseyNumber: "4",
    contactNumber: "+94 77 444 5555",
    status: "Active",
    email: "emily.davis@netninjas.com",
    dateOfBirth: "2001-03-15",
    gender: "Female",
    height: "172",
    weight: "62",
    address: "89 Porutota Road, Negombo",
    photoUrl: null
  },
  {
    id: "PL-2026-005",
    name: "David Martinez",
    team: "Beach Blazers",
    position: "Spiker",
    jerseyNumber: "11",
    contactNumber: "+94 77 555 6666",
    status: "Inactive",
    email: "david.martinez@beachblazers.com",
    dateOfBirth: "1998-07-30",
    gender: "Male",
    height: "190",
    weight: "88",
    address: "12 Beach Road, Matara",
    photoUrl: null
  },
  {
    id: "PL-2026-006",
    name: "Lisa Thompson",
    team: "Court Kings",
    position: "Setter",
    jerseyNumber: "3",
    contactNumber: "+94 77 666 7777",
    status: "Active",
    email: "lisa.thompson@courtkings.com",
    dateOfBirth: "2003-01-20",
    gender: "Female",
    height: "175",
    weight: "65",
    address: "56 Flower Road, Colombo 07",
    photoUrl: null
  }
];

export const baseStats = {
  totalPlayers: 512,
  activePlayers: 489,
  teamsCovered: 64,
  recentlyAdded: 24
};
