export const initialTournaments = [
  {
    id: "TR-2026-001",
    name: "Spring Championship 2026",
    location: "Central Complex, Colombo",
    city: "Colombo",
    startDate: "2026-02-01",
    endDate: "2026-03-06",
    teamsCount: 16,
    status: "Ongoing",
    type: "Round Robin",
    category: "Men's Senior",
    description: "The primary spring season division championship for senior men's volleyball clubs nationwide.",
    registrationDeadline: "2026-01-15",
    organizerName: "National Volleyball Association",
    teamLimit: 16,
    groupsCount: 4,
    matchFormat: "Best of 5 Sets",
    setRules: "25 Point Rally Score",
    notes: "Top two teams from each group qualify for knockout stages.",
    bannerUrl: null,
    publicVisibility: true,
    allowReportSharing: true,
    enableLeaderboard: true
  },
  {
    id: "TR-2026-002",
    name: "Regional Cup",
    location: "Municipal Arena, Kandy",
    city: "Kandy",
    startDate: "2026-04-10",
    endDate: "2026-04-18",
    teamsCount: 8,
    status: "Upcoming",
    type: "Knockout",
    category: "Premier Division",
    description: "Regional cup tournament for premier division clubs competing in central province.",
    registrationDeadline: "2026-03-25",
    organizerName: "Central Province Volleyball Board",
    teamLimit: 8,
    groupsCount: 2,
    matchFormat: "Best of 5 Sets",
    setRules: "25 Point Rally Score",
    notes: "Matches will be televised live locally.",
    bannerUrl: null,
    publicVisibility: true,
    allowReportSharing: true,
    enableLeaderboard: true
  },
  {
    id: "TR-2026-003",
    name: "National Schools League",
    location: "Vincent Indoor Gym, Galle",
    city: "Galle",
    startDate: "2026-01-03",
    endDate: "2026-01-20",
    teamsCount: 12,
    status: "Completed",
    type: "Double Elimination",
    category: "Under 19",
    description: "Annual national volleyball competition for top-tier school teams.",
    registrationDeadline: "2025-12-15",
    organizerName: "Schools Sports Council",
    teamLimit: 12,
    groupsCount: 2,
    matchFormat: "Best of 3 Sets",
    setRules: "21 Point Rally Score",
    notes: "Standard high school division eligibility applies.",
    bannerUrl: null,
    publicVisibility: true,
    allowReportSharing: true,
    enableLeaderboard: true
  },
  {
    id: "TR-2026-004",
    name: "Summer Beach Volleyball",
    location: "Sandy Beach Park, Negombo",
    city: "Negombo",
    startDate: "2026-05-15",
    endDate: "2026-05-22",
    teamsCount: 10,
    status: "Upcoming",
    type: "Double Elimination",
    category: "Men's Open",
    description: "Negombo beach volleyball carnival featuring senior mens beach double formats.",
    registrationDeadline: "2026-05-01",
    organizerName: "Negombo Beach Sports Club",
    teamLimit: 12,
    groupsCount: 0,
    matchFormat: "Best of 3 Sets",
    setRules: "21 Point Rally Score",
    notes: "Standard FIVB beach volleyball guidelines apply.",
    bannerUrl: null,
    publicVisibility: true,
    allowReportSharing: true,
    enableLeaderboard: true
  },
  {
    id: "TR-2026-005",
    name: "University Championship",
    location: "University Courts, Colombo",
    city: "Colombo",
    startDate: "2026-03-20",
    endDate: "2026-04-05",
    teamsCount: 14,
    status: "Ongoing",
    type: "Round Robin",
    category: "Mixed Senior",
    description: "Inter-university tournament promoting sportsmanship and team volleyball.",
    registrationDeadline: "2026-03-01",
    organizerName: "University Sports Association",
    teamLimit: 16,
    groupsCount: 4,
    matchFormat: "Best of 5 Sets",
    setRules: "25 Point Rally Score",
    notes: "Valid student registration cards are mandatory for all rosters.",
    bannerUrl: null,
    publicVisibility: true,
    allowReportSharing: true,
    enableLeaderboard: true
  },
  {
    id: "TR-2026-006",
    name: "Winter Invitational",
    location: "Jaffna Stadium, Jaffna",
    city: "Jaffna",
    startDate: "2025-11-12",
    endDate: "2025-11-20",
    teamsCount: 8,
    status: "Completed",
    type: "Knockout",
    category: "Men's Senior",
    description: "Annual winter cup inviting top clubs across provinces.",
    registrationDeadline: "2025-10-25",
    organizerName: "Jaffna Volleyball Association",
    teamLimit: 8,
    groupsCount: 2,
    matchFormat: "Best of 5 Sets",
    setRules: "25 Point Rally Score",
    notes: "Inaugural northern province showcase.",
    bannerUrl: null,
    publicVisibility: true,
    allowReportSharing: true,
    enableLeaderboard: true
  },
  {
    id: "TR-2026-007",
    name: "Coastal Classic",
    location: "Beach Park, Trincomalee",
    city: "Trincomalee",
    startDate: "2026-06-05",
    endDate: "2026-06-12",
    teamsCount: 12,
    status: "Upcoming",
    type: "Round Robin",
    category: "Women's Open",
    description: "Beach tournament on the scenic eastern coast.",
    registrationDeadline: "2026-05-20",
    organizerName: "Eastern Coast Volleyball Club",
    teamLimit: 16,
    groupsCount: 4,
    matchFormat: "Best of 3 Sets",
    setRules: "21 Point Rally Score",
    notes: "Prizing includes travel trophies and sponsorships.",
    bannerUrl: null,
    publicVisibility: true,
    allowReportSharing: true,
    enableLeaderboard: true
  },
  {
    id: "TR-2026-008",
    name: "Mayor's Trophy",
    location: "Indoor Gym, Kurunegala",
    city: "Kurunegala",
    startDate: "2025-12-10",
    endDate: "2025-12-18",
    teamsCount: 16,
    status: "Completed",
    type: "Knockout",
    category: "Men's Senior",
    description: "Annual municipal tournament sponsored by the Kurunegala Mayor's office.",
    registrationDeadline: "2025-11-25",
    organizerName: "Kurunegala Municipal Council",
    teamLimit: 16,
    groupsCount: 4,
    matchFormat: "Best of 5 Sets",
    setRules: "25 Point Rally Score",
    notes: "Prizes awarded by the municipal commissioner.",
    bannerUrl: null,
    publicVisibility: true,
    allowReportSharing: true,
    enableLeaderboard: true
  },
  {
    id: "TR-2026-009",
    name: "Independence Cup",
    location: "District Courts, Gampaha",
    city: "Gampaha",
    startDate: "2026-02-20",
    endDate: "2026-03-10",
    teamsCount: 12,
    status: "Ongoing",
    type: "Round Robin",
    category: "Men's Senior",
    description: "Celebrating national independence anniversary with a premier league division contest.",
    registrationDeadline: "2026-02-05",
    organizerName: "Gampaha Volleyball Union",
    teamLimit: 12,
    groupsCount: 2,
    matchFormat: "Best of 5 Sets",
    setRules: "25 Point Rally Score",
    notes: "Opening ceremony will feature local cultural dances.",
    bannerUrl: null,
    publicVisibility: true,
    allowReportSharing: true,
    enableLeaderboard: true
  },
  {
    id: "TR-2026-010",
    name: "Junior National Championship",
    location: "Sports Ground, Anuradhapura",
    city: "Anuradhapura",
    startDate: "2026-07-01",
    endDate: "2026-07-08",
    teamsCount: 16,
    status: "Upcoming",
    type: "Round Robin",
    category: "Under 17",
    description: "Annual tournament to scout rising youth talents for national squads.",
    registrationDeadline: "2026-06-15",
    organizerName: "Youth Sports Ministry",
    teamLimit: 16,
    groupsCount: 4,
    matchFormat: "Best of 3 Sets",
    setRules: "21 Point Rally Score",
    notes: "Age verification checks will happen 1 day prior.",
    bannerUrl: null,
    publicVisibility: true,
    allowReportSharing: true,
    enableLeaderboard: true
  },
  {
    id: "TR-2026-011",
    name: "Provincial Shield",
    location: "Indoor Arena, Ratnapura",
    city: "Ratnapura",
    startDate: "2025-10-05",
    endDate: "2025-10-12",
    teamsCount: 8,
    status: "Completed",
    type: "Knockout",
    category: "Men's Senior",
    description: "Regional tournament crowning the southern province club shield holders.",
    registrationDeadline: "2025-09-20",
    organizerName: "Sabaragamuwa Volleyball Union",
    teamLimit: 8,
    groupsCount: 2,
    matchFormat: "Best of 5 Sets",
    setRules: "25 Point Rally Score",
    notes: "Gems & Jewelry Board is the main shield sponsor.",
    bannerUrl: null,
    publicVisibility: true,
    allowReportSharing: true,
    enableLeaderboard: true
  },
  {
    id: "TR-2026-012",
    name: "Clubs Championship",
    location: "Municipal Courts, Badulla",
    city: "Badulla",
    startDate: "2025-09-15",
    endDate: "2025-09-22",
    teamsCount: 12,
    status: "Completed",
    type: "Double Elimination",
    category: "Mixed Senior",
    description: "Annual mixed team challenge for nationwide sports clubs.",
    registrationDeadline: "2025-08-30",
    organizerName: "Badulla Sports League",
    teamLimit: 12,
    groupsCount: 2,
    matchFormat: "Best of 3 Sets",
    setRules: "21 Point Rally Score",
    notes: "Co-ed formats require minimum 2 players of opposite gender.",
    bannerUrl: null,
    publicVisibility: true,
    allowReportSharing: true,
    enableLeaderboard: true
  }
];

export const getTournamentByRouteId = (routeId) => {
  const saved = localStorage.getItem("volleyreel_tournaments");
  let list = initialTournaments;
  if (saved) {
    try {
      const parsed = JSON.parse(saved);
      if (Array.isArray(parsed)) {
        list = parsed;
      }
    } catch (e) {
      console.error(e);
    }
  }
  return list.find((t) => t.id === routeId) || null;
};
